pipelines:
  custom:
    publish-to-LIVE:
      - step:
          name: Build jar file
          image: maven:3.6.0-jdk-11
          script:
            - mvn -B clean compile assembly:single
          artifacts:
            - target/AWSLambda_XSLTTransform-1.0-SNAPSHOT-jar-with-dependencies.jar
            - config/*

      - step:
          name: Deploy lambda function & web resources ($LIVE version)
          image: atlassian/default-image:2
          script:
            # Set function environment variable configuration to LIVE
            - pipe: atlassian/aws-lambda-deploy:0.5.7
              variables:
                AWS_DEFAULT_REGION: "eu-west-1"
                FUNCTION_NAME: 'AWSLambda_CUDLPackageDataJSON_AddEvent'
                COMMAND: 'update'
                FUNCTION_CONFIGURATION: 'config/lambdafunction.live.json'
                ZIP_FILE: 'target/AWSLambda_XSLTTransform-1.0-SNAPSHOT-jar-with-dependencies.jar'

            # Deploy jar to lambda function ($LATEST/Dev version)
            - pipe: atlassian/aws-lambda-deploy:0.5.7
              variables:
                AWS_DEFAULT_REGION: "eu-west-1"
                FUNCTION_NAME: 'AWSLambda_CUDLPackageDataJSON_AddEvent'
                COMMAND: 'update'
                ZIP_FILE: 'target/AWSLambda_XSLTTransform-1.0-SNAPSHOT-jar-with-dependencies.jar'

            # Tag as LIVE
            - pipe: atlassian/aws-lambda-deploy:0.5.7
              variables:
                AWS_DEFAULT_REGION: "eu-west-1"
                FUNCTION_NAME: 'AWSLambda_CUDLPackageDataJSON_AddEvent'
                COMMAND: 'alias' # 'alias' or 'update'
                ALIAS: 'LIVE'

            # Copy web resources to s3 cudl-transcriptions (Staging)
            - pipe: atlassian/aws-s3-deploy:0.4.5
              variables:
                AWS_DEFAULT_REGION: "eu-west-1"
                S3_BUCKET: "cudl-transcriptions-staging/cudl-resources"
                LOCAL_PATH: "src/main/resources/web/cudl-resources"
                EXTRA_ARGS: "--size-only"
                DELETE_FLAG: "true"
                
            # Copy web resources to s3 cudl-transcriptions (LIVE)
            - pipe: atlassian/aws-s3-deploy:0.4.5
              variables:
                AWS_DEFAULT_REGION: "eu-west-1"
                S3_BUCKET: "cudl-transcriptions/cudl-resources"
                LOCAL_PATH: "src/main/resources/web/cudl-resources"
                EXTRA_ARGS: "--size-only"
                DELETE_FLAG: "true"                
  branches:
    master:
      - step:
          name: Build jar file
          image: maven:3.6.0-jdk-11
          script:
            - mvn -B clean compile assembly:single
          artifacts:
            - target/AWSLambda_XSLTTransform-1.0-SNAPSHOT-jar-with-dependencies.jar
            - config/*

      - step:
          name: Deploy lambda function & web resources ($LATEST/Dev version)
          image: atlassian/default-image:2
          # trigger: manual
          script:
            # Deploy jar to lambda function ($LATEST/Dev version)
            - pipe: atlassian/aws-lambda-deploy:0.5.7
              variables:
                AWS_DEFAULT_REGION: "eu-west-1"
                FUNCTION_NAME: 'AWSLambda_CUDLPackageDataJSON_AddEvent'
                COMMAND: 'update' # 'alias' or 'update'
                ZIP_FILE: 'target/AWSLambda_XSLTTransform-1.0-SNAPSHOT-jar-with-dependencies.jar'
                FUNCTION_CONFIGURATION: 'config/lambdafunction.dev.json'
                # Alias variables
                # ALIAS: '<string>'
                # VERSION: '<string>'
                # FUNCTION_CONFIGURATION: "<string>" # Optional

              # Copy resources to s3 cudl-transcriptions-dev
            - pipe: atlassian/aws-s3-deploy:0.4.5
              variables:
                AWS_DEFAULT_REGION: "eu-west-1"
                S3_BUCKET: "cudl-transcriptions-dev/cudl-resources"
                LOCAL_PATH: "src/main/resources/web/cudl-resources"
                EXTRA_ARGS: "--size-only"
                DELETE_FLAG: "true"
                # CONTENT_ENCODING: '<string>' # Optional.
                # ACL: '<string>' # Optional.
                # STORAGE_CLASS: '<string>' # Optional.
                # CACHE_CONTROL: '<string>' # Optional.
                # EXPIRES: '<timestamp>' # Optional.
                # DEBUG: '<boolean>' # Optional.